# This YAML is the default template and can be modified based on this 
---
version: 2.0
steps:
  PRE_BUILD:
  - checkout:
      name: "checkout"
      inputs:
        scm: "codehub"
        url: "git@codehub.devcloud.ap-southeast-3.huaweicloud.com:huaweicloud-samples00001/huaweicloud-samples.git"
        branch: "${codeBranch}"
        lfs: false
        submodule: false
  BUILD:
  - sh:
      name: "sh"
      inputs:
        command: "echo hello"
